// <auto-generated />
using System;
using RevisaFacil.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RevisaFacil.Migrations
{
    [DbContext(typeof(EstudoDbContext))]
    partial class EstudoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("RevisaFacil.Models.Assunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Int1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Int2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Int3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Int4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Int5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Rev1Concluida")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Rev2Concluida")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Rev3Concluida")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Rev4Concluida")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Rev5Concluida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Assuntos");
                });

            modelBuilder.Entity("RevisaFacil.Models.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intervalo1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intervalo2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intervalo3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intervalo4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intervalo5")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Configuracoes");
                });

            modelBuilder.Entity("RevisaFacil.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("RevisaFacil.Models.Assunto", b =>
                {
                    b.HasOne("RevisaFacil.Models.Disciplina", "Disciplina")
                        .WithMany("Assuntos")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("RevisaFacil.Models.Disciplina", b =>
                {
                    b.Navigation("Assuntos");
                });
#pragma warning restore 612, 618
        }
    }
}
